wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.1
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703397278.694282
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.11.3
      5: 0.16.1
      8:
      - 1
      - 5
      13: darwin-arm64
