wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.1
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703567966.407
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      2:
      - 5
      - 8
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.3
      5: 0.16.1
      8:
      - 4
      - 6
      13: darwin-arm64
